### ISSUE TITLE
Package Maintainer Handover page missing but linked to

### ISSUE THREAD

**Issue by pauby** [chocolatey/choco-wiki#102]
The Package Maintainer Handover page is missing but is currently being linked to on the [Package Triage Process](https://github.com/chocolatey/choco/wiki/PackageTriageProcess#new-maintainers) page and the [Create Packages](https://github.com/chocolatey/choco/wiki/CreatePackages#becoming-a-primary-maintainer-of-an-existing-package) page but the page being linked to does not exist and should be created.

**Comment by AdmiringWorm** [comment]
Actually, it does exist.
However, there is a typo in the link itself.
On both pages the link is: `PackageMantainerHandover`, but should be [`PackageMaintainerHandover`](https://github.com/chocolatey/choco/wiki/PackageMaintainerHandover).

**Comment by pauby** [comment]
@AdmiringWorm you know that more than one of us didn't spot that 😊 Thanks for having better eyes! Just need to raise a PR to get it amended and this can be closed.

**Comment by AdmiringWorm** [comment]
@pauby TBH, I didn't notice the typo at first either.
But I somehow found the package it was supposed to link to, and had to compare the links to figure out the difference.

> Just need to raise a PR to get it amended and this can be closed.

On it. Found a couple of new places where it has the same typo, I'll fix those at the same time.

**Comment by pauby** [comment]
Cheers @AdmiringWorm. A missing 'i' and nobody spotted it 👍
