### ISSUE TITLE
Package Maintainer Handover page missing but linked to

### ISSUE THREAD

**Issue by pauby** [chocolatey/choco-wiki#103]
There are links on [Create Packages](https://github.com/chocolatey/choco/wiki/CreatePackages#becoming-a-primary-maintainer-of-an-existing-package) page and also on the [Package Triage Process](https://github.com/chocolatey/choco/wiki/PackageTriageProcess#new-maintainers) page to the Package Maintainer Handover page, however the page itself does not exist. Needs to be created.

**Comment by gep13** [comment]
This is a duplicate of this right: https://github.com/chocolatey/choco-wiki/issues/102

Assuming that this was done during the GitHub disruptions.

**Comment by pauby** [comment]
It is - I created this again as it was giving me a 404 on viewing 102. Sods law it now works. Didn't know they had disruptions but that sounds like it could be the issue.

**Comment by gep13** [comment]
GitHub was having issues pretty much the whole of yesterday, which started on Sunday evening:

https://status.github.com/messages
