### ISSUE TITLE
Stop recommending rawgit

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/choco-wiki#106]
Considering that rawgit will be shutting down next year, and since they no longer allows adding new urls (well, not trought the website).

I would suggest to either remove the suggestion on the [CreatePackages](https://github.com/chocolatey/choco/wiki/CreatePackages#package-icon-guidelines), or change it to use a different provider (in this case, I suggest jsdelivr).

I'm willing to open a PR to change it to jsdelivr, if acceptable.

**NOTE:** Originally reported over at https://github.com/chocolatey/choco/issues/1682

**Comment by FranklinYu** [comment]
I think we should also change the template:

https://github.com/chocolatey/choco/blob/ea4b155ad4f6911c003fcf30792f85abca480f05/src/chocolatey/infrastructure.app/templates/NuspecTemplate.cs#L62

**Comment by gep13** [comment]
@FranklinYu that would a separate issue.  Can you please raise an issue in that repository as well?

**Comment by FranklinYu** [comment]
@bcurran3 I don't think there is multiple. Among the four alternatives listed on RawGit site:

 1. GitHub Pages is valid choice, but I don't want to enable GitHub Project just because of this. I think many people share this opinion.
 2. CodeSandbox is not related at all.
 3. unpkg only works for npm packages, not GitHub files.

**Comment by bcurran3** [comment]
Don't a quick little research now...

Others that look viable at a glance:
https://min.gitcdn.link/
https://www.staticaly.com/
https://raw.githack.com/
https://gitcdn.link/

I've tried all once with a PNG file. All have paste in your link, copy and paste out the converted link.

**Comment by bcurran3** [comment]
FYI: I've standardized all my new and updated packages to use the Staticaly CDN and so far I'm happy with the results.

I've even added checking rawgit links in my new nuspec checker script and recommend the three CDNs above when found.

Not through moderation yet, but if you want a sneak peek:
https://chocolatey.org/packages/choco-nuspec-checker

**Comment by FranklinYu** [comment]
Any input from @pauby or even @ferventcoder? Shall we start working on a Pull Request?

**Comment by pauby** [comment]
@FranklinYu I'm not sure what input you need? I would suggest putting a PR together with a selection of choices for people to decide for themselves. the [.nuspec template](https://github.com/chocolatey/choco-wiki/issues/106#issuecomment-447680455) should point to that page.

One option that hasn't been mentioned so far is jsdelivr.com (it's not just for npm / Javascript projects).

**Comment by AdmiringWorm** [comment]
@pauby actually jsdelivr was mentioned in the first post. Just not with `.com`

**Comment by bcurran3** [comment]
For anyone interested, CNC (https://chocolatey.org/packages/choco-nuspec-checker) v2019.02.04 can auto-magically convert your old RawGit links to Staticaly (default), GitHack, GitCDN, or jsDelivr. 

![image](https://user-images.githubusercontent.com/14026600/52257335-499edc80-28cf-11e9-92e0-9818f74925bd.png)

I know this isn't relevant to the docs, but this util does make it easy to update your nuspec files' URLs away from RawGit.

**Comment by FranklinYu** [comment]
It has been half a year and I think we can have a conclusion. Among the 4 possibilities, I prefer jsDelivr because:

1. Multi-CDN means better coverage.
2. More famous than Staticaly.

**Comment by gep13** [comment]
@FranklinYu are you in a position to help with creating a PR for the change?

**Comment by pauby** [comment]
The choices I've seen being used in packages so far are (in no particular order):

* jsdelivr.com
* staticaly.com
* githack.com

There is another one that escapes me. If / when I find I'll update here. But I think we should be clear there are others that can be used. The purpose of giving examples is to help people who don't know what to choose.

**Comment by pauby** [comment]
If nobody wants to put a PR in I'll do it this weekend.

**Comment by AdmiringWorm** [comment]
@pauby feel free, I won't be able to even look at creating a PR any time soon :disappointed:

**Comment by pauby** [comment]
@AdmiringWorm Cheers for letting me know. I also don't want to step on @FranklinYu 's toes either, so to speak. 😄

**Comment by gep13** [comment]
@pauby has put in a PR for this, and it will be pushed to production soon.
