### ISSUE TITLE
Confusing non-admin installation documentation

### ISSUE THREAD

**Issue by pbb72** [chocolatey/choco-wiki#135]
There are several problems with the current documentation for installing Chocolatey without admin rights (https://chocolatey.org/install#non-administrative-install):

1. The documentation is inside a "hidden" section of the page, which requires JavaScript and a click interaction to display. On several occasions, following outgoing links and then coming back to the documentation, the whole section had disappeared. Also, it's not possible to use Ctrl-F to search for content when the section is hidden. If this "advanced documentation" should not be included in the base page, then it would be better to create a separate page instead of relying on some custom JavaScript code.
1. Even though there is a 3-step instruction for non-administrative install, it seems to me that it's really identical to installing to a different location. Why not just pointing that out?
1. Point 3 in the instructions says "Here is an example of this", without making clear what "this" refers to. I initially thought the supplied NonAdmin.ps1 was meant to be used as a replacement for the default install.ps1.
1. The example code starts with setting an environment variable "ChocolateyInstall", even though step 1 already provided documentation for doing that. Is this just repeating the same procedure again, or is this separate and should be included?
1. The code provides a commented-out line for PowerShell 3+. Even though the documentation hasn't been updated in 2 years, I think PS5 was the current version when it was written. Do most PowerShell users stick to v.2? Why is there even a 3+ line when PowerShell is backwards compatible? This line could use some documentation as to why it is included.
1. While much of the code of the example is rather cryptic, it's is obvious that the second half starts installing packages. Which brings up the question, is this code meant as an example for installing Chocolatey itself, or for how to install packages? Why would one combine installing Chocolatey and packages in one code file? Do most users only every run Chocolatey once, to install their favorite packages, and then never touch it again?

**Comment by ferventcoder** [comment]
> The documentation is inside a "hidden" section of the page, which requires JavaScript and a click interaction to display. On several occasions, following outgoing links and then coming back to the documentation, the whole section had disappeared. Also, it's not possible to use Ctrl-F to search for content when the section is hidden. If this "advanced documentation" should not be included in the base page, then it would be better to create a separate page instead of relying on some custom JavaScript code.

I agree with this - I am a bit wary that a direct link isn't working, as we worked on that. So when you have a link and you go to that (not navigating back/forward buttons in the browser), it should open the hidden section and navigate right to it. Otherwise there is a bug.

**Comment by ferventcoder** [comment]
> Even though there is a 3-step instruction for non-administrative install, it seems to me that it's really identical to installing to a different location. Why not just pointing that out?

Will be sure to do that.

**Comment by ferventcoder** [comment]
> Point 3 in the instructions says "Here is an example of this", without making clear what "this" refers to. I initially thought the supplied NonAdmin.ps1 was meant to be used as a replacement for the default install.ps1.

Fixing this as part of #142

**Comment by ferventcoder** [comment]
> The example code starts with setting an environment variable "ChocolateyInstall", even though step 1 already provided documentation for doing that. Is this just repeating the same procedure again, or is this separate and should be included?

Will look to adjust that.

**Comment by ferventcoder** [comment]
> The code provides a commented-out line for PowerShell 3+. Even though the documentation hasn't been updated in 2 years, I think PS5 was the current version when it was written. Do most PowerShell users stick to v.2? Why is there even a 3+ line when PowerShell is backwards compatible? This line could use some documentation as to why it is included.

I'm removing that - also updating the notes on PowerShell v3+ that it's only there for folks who want something easier to remember.

**Comment by ferventcoder** [comment]
> While much of the code of the example is rather cryptic, it's is obvious that the second half starts installing packages. Which brings up the question, is this code meant as an example for installing Chocolatey itself, or for how to install packages? Why would one combine installing Chocolatey and packages in one code file? Do most users only every run Chocolatey once, to install their favorite packages, and then never touch it again?

Splitting into two files

**Comment by ferventcoder** [comment]
Completed - is live at https://github.com/chocolatey/wiki now, and will be live on the website after next docs push.

**Comment by ferventcoder** [comment]
Related to #142
