### ISSUE TITLE
Update non-admin to account for powershell execution policy

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco-wiki#142]
Sometimes folks may not know how to adjust the PSH execution policy - ensure we provide that as a note in the non-admin installation section

**Comment by ferventcoder** [comment]
Completed - is live at https://github.com/chocolatey/wiki now, and will be live on the website after next docs push.
Related to #135.

**Comment by pauby** [comment]
That URL you posted is missing a bit - https://github.com/chocolatey/choco/wiki
