### ISSUE TITLE
choco

### ISSUE THREAD

**Issue by ambf1436** [chocolatey/choco-wiki#15]
leave a commit

**Comment by gep13** [comment]
@ambf1436 just wanted to check in here to see what the intention of this issue is?  Are you having a problem?

If so, can you provide some more information?

**Comment by dragon788** [comment]
@gep13 I think this can be closed, I have a feeling they were testing the GitHub API and didn't close the comment/issue automatically or cleanup after.

**Comment by gep13** [comment]
>@dragon788 said...
@gep13 I think this can be closed, I have a feeling they were testing the GitHub API and didn't close the comment/issue automatically or cleanup after.

I think you might be right.

@ambf1436  Please re-open this issue if you are still having a problem.
