### ISSUE TITLE
AU setup instructions unclear/ambiguous/incomplete

### ISSUE THREAD

**Issue by lackovic** [chocolatey/choco-wiki#169]
Setting up my first repo and following the instructions found on [Chocolatey Automatic Packaging for Maintenance documentation](https://chocolatey.org/docs/automatic-packages) I noticed some inconsistencies, missing steps and duplicated information.

I created [this PR](https://github.com/chocolatey/choco-wiki/pull/168) and proposed some changes based on my findings.

**Comment by pauby** [comment]
I'm wondering if we should slim down the documentation on the website around AU, give a general overview but point to the specific documentation on the AU GitHub page. That would make it clear that AU is a community maintained project and would free us from keeping it up to date with any changes in AU itself.

Thoughts?

**Comment by ferventcoder** [comment]
This has been merged. I believe a lot of what was done here did reduce our documentation surrounding AU @pauby - if you believe there is more to be done, let's create a new issue. 👍
