### ISSUE TITLE
external program failed (msbuild.exe)

### ISSUE THREAD

**Issue by hjungG** [chocolatey/choco-wiki#18]
I fetched latest choco, ran build.bat and got a build failure. See the log below.
My machine installed .net 4.5.1
Anyone can help? 
Thanks in advance.

= = = = = = = = = = = = = = = = = = = = 
                 [echo] Setting compile variables
                 [echo] Finding and restoring all packages (C:\chocolatey.0.9.9.12\choco\lib\NuGet\NuGet.exe restore 'C:\chocolatey.0.9.9.12\choco\src\chocolatey.sln')
                 [exec] Unable to find version '1.1.86' of package 'coveralls.io'.
                 [exec] C:\chocolatey.0.9.9.12\choco\.build\compile.step(66,6):
                 [exec] External Program Failed: C:\chocolatey.0.9.9.12\choco\lib\NuGet\NuGet.exe (return code was 1)
                 [echo] Compiling C:\chocolatey.0.9.9.12\choco\src\chocolatey.sln.
                 [echo] Building on 4.0

            C:\chocolatey.0.9.9.12\choco\.build\compile.step(173,14):
            Failed to start MSBuild.
                C:\chocolatey.0.9.9.12\choco\.build\compile.step(173,14):
                External Program Failed: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe (return code was 1)

**Comment by ferventcoder** [comment]
Definitely the wrong repository to ask on.

**Comment by ferventcoder** [comment]
I would head over to chocolatey/choco and pose your question - it's better to reach out over gitter though.

**Comment by ferventcoder** [comment]
You will find a link to gitter in the readme.
