### ISSUE TITLE
Documentation required for QDE phase 2

### ISSUE THREAD

**Issue by vexx32** [chocolatey/choco-wiki#207]
Quite a lot has changed for QDEv2 and setup has been simplified quite a bit, so docs will need to be updated to reflect that.

We'll need to retain the V1 documentation for the folks who are still using using as well, so we'll need to keep both copies of the documentation around.

**Comment by vexx32** [comment]
Internal issue note from @adilio:

> To follow-up here, what ended up needing fixed was also the Network Profile of the NIC. Windows wants to set it as Public by default, and then Windows Firewall will step in and shut down all access. Normally not a huge issue, but when you're hitting this from an external IP, all the choco install and choco push commands fall down.

This should be included as a note in the firewall docs for V2 as well. It's a less common scenario which won't occur if the QDE VM is joined to a domain, but worth noting nonetheless.

**Comment by ferventcoder** [comment]
Great job, closing this off!
