### ISSUE TITLE
Weirdness while installing a package and a game on Steam at the same time

### ISSUE THREAD

**Issue by Hariador** [chocolatey/choco-wiki#22]
So I just installed Chocolately and I was installing my first package.  
At the same time I was downloading something through Steam.  

![image](https://cloud.githubusercontent.com/assets/919939/16604235/0807a3b8-42d8-11e6-9c99-d3674a88145c.png)

**Comment by ferventcoder** [comment]
You should only install one thing at a time. Otherwise it can cause issues with not just Chocolatey, but possibly Windows.

**Comment by ferventcoder** [comment]
Interesting error though, did you log it somewhere else?
