### ISSUE TITLE
CCM Scheduling documentation screenshots need to be amended

### ISSUE THREAD

**Issue by pauby** [chocolatey/choco-wiki#237]
It was noticed that one of the screenshots in the CCM Scheduling documentation.

@ferventcoder Can you add more information around which screenshot it is and what needs to be fixed?

**Comment by vexx32** [comment]
Any screenshots which show the scheduling UI will need to be updated, they were taken on an older build.

**Comment by ferventcoder** [comment]
There is only one that I recall that definitely needed updated. Let me grab that location here.

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/choco-wiki/blob/master/images/deployments/ccm-deployments-set-schedule-datetime.png is the image that definitely needs updated
