### ISSUE TITLE
Link overflow in website FAQ

### ISSUE THREAD

**Issue by ChrisMaddock** [chocolatey/choco-wiki#27]
https://chocolatey.org/docs/chocolatey-faqs

A link isn't closed properly at the start of the "What distinction does Chocolatey make between an installable and a portable application?".

It seems to be caused by a HTML anchor tag in the markdown - although I'm not sure why it's there, so didn't try to fix it!

```
<a name="AppVsTool" />
### What distinction does Chocolatey make between an installable and a portable application?
#### Installable application
```

**Comment by ferventcoder** [comment]
Thanks for noticing that. Fixing it.

**Comment by ferventcoder** [comment]
Fixed in https://github.com/chocolatey/choco-wiki/commit/ac49bc8a82d498d9ad1dfe40a9df0503c33bc803
