### ISSUE TITLE
Make requirements more prominent

### ISSUE THREAD

**Issue by teknowledgist** [chocolatey/choco-wiki#43]
The requirements to install Chocolatey should be at or near the top of the document, not between information about installing behind a proxy and the mini-FAQ.  

Also, the Requirements section states that "the installation will attempt to install .NET 4.0 if you do not have it installed", but it sure doesn't do that for me, and I don't see where *install.ps1* is doing that.  (Is it?)  Instead, Chocolatey happily installs without error and then promptly fails when you try to use it.

If .NET is an up-front requirement that all users (even ones who will give up when they read "restricted TLS") will recognize, then there is no need for the *install.ps1* to attempt to install it, but when the requirements are buried and an incorrect(?) claim is made, a lot of potential users will give up.

**Comment by ferventcoder** [comment]
@teknowledgist https://github.com/chocolatey/choco/blob/946367a6c263cc2d1b3beec5e6b771404d5f0436/nuget/chocolatey/tools/chocolateysetup.psm1#L642-L695 is where you will find the attempted install for .NET 4.0.

Installed may also mean reboot before able to use. So if Chocolatey installs, it will detect whether .NET 4.x is installed, not whether it is currently available. Which means it will error when you try to use it until you reboot the system.

**Comment by ferventcoder** [comment]
The entire Install is about to get a revamp. Thanks for this as it helps determine what will show by default and what will be hidden behind a toggle. Lots of folks complain because they see the install page and think the process is involved when there are really lots of options.

**Comment by ferventcoder** [comment]
I did notice that those are http calls. Fixing.

**Comment by teknowledgist** [comment]
Boy do I feel naive!  

I am not seeing .NET get installed via the Chocolatey install on a bare-bones Win7x64 system, and I was looking for the .NET install directly in the initial script which is -- of course -- far too simple on its own to handle installing everything Chocolatey does.  

Thanks for being patient with me.

**Comment by ferventcoder** [comment]
Done with https://github.com/chocolatey/choco-wiki/commit/830ad16176266f5b47f441e939a7792bcb628bd8
