### ISSUE TITLE
Issues with How-To-Parse-PackageParameters-Argument.md

### ISSUE THREAD

**Issue by Schroedingers-Cat** [chocolatey/choco-wiki#57]
I'm trying to create chocolatey packages that support package parameters. However, I'm struggling with the documentation at https://github.com/chocolatey/choco-wiki/blob/master/How-To-Parse-PackageParameters-Argument.md

1. The link in the first paragraph is dead https://github.com/chocolatey/choco-wiki/blob/master/CommandsInstall
2. The sentence `NOTE: See #312 for Chocolatey v0.9.10 adding a helper to do the below with almost no boilerplate.` made me think I'd find info in that issue about some newly developed helper functions making the below example more easier to achieve. After reading through it, it looks like a discussion about how to improve the situation (mentioning native powershell parameters), but it doesn't look like something actually improved. So why is it useful to read that issue if you want to understand how it currently works?
3. I'm trying to implement the given example into a new package. This is the content of my "chocolateyinstall.ps1" file http://pastebin.com/xJh8F0VV
As you can see, I'm using exactly the same code, just searching for two custom parameters. However, when building the package and installing it via `choco install packagename.nupkg -y -f -packageParameters '"/vst2:1 /vst3:0"'`, the lines 47 and 52 should trigger a warning and an error in the console but they don't. What am I doing wrong here?

I appreciate any help!

**Comment by ferventcoder** [comment]
All fixed up - https://groups.google.com/d/msgid/chocolatey/e1b7f133-ef10-45dc-89b7-2ab14585da43%40googlegroups.com
