### ISSUE TITLE
How-To-Deprecate-A-Chocolatey-Package requires tools dir with an empty file

### ISSUE THREAD

**Issue by dhoer** [chocolatey/choco-wiki#69]
The step:
> Remove all files except the .nuspec from the Chocolatey Package.  

Will result in package error if files section of .nuspec is pointing to tools directory. Removing the files section will pull in .git files. Updating files section exclude .git folder will not work either.

Based on @admiringworm:

```
<files>
</files>
```
or 
```
<files />
```

Will prevent the scm files from getting included in package.

**Comment by dhoer** [comment]
So maybe the verbiage can be something like:

> Remove all files except the .nuspec from the Chocolatey Package and update .nuspec files tag to be just `<files />`.

**Comment by dhoer** [comment]
I don't like that either...

Maybe 

> Remove all files except the .nuspec from the Chocolatey Package.
> Remove any `<file>` tags from `<files>` section in .nuspec to ensure scm files (e.g., .git) are not included in the package.

**Comment by ferventcoder** [comment]
What ever works and makes the most sense (and is the easiest path here if it makes sense as well) is what I would recommend. So which ever works. Did `<files />` not work?

**Comment by dhoer** [comment]
The `<files />` tag worked as well.
