### ISSUE TITLE
Variable reference is not valid. ':' was not followed by a valid variable name character.

### ISSUE THREAD

**Issue by dhoer** [chocolatey/choco-wiki#75]
Parameter password example is not valid and will throw the following:

> Variable reference is not valid. ':' was not followed by a valid variable name character. Consider using ${} to delimit the name.

https://github.com/chocolatey/choco-wiki/search?utf8=%E2%9C%93&q=%24pp%5B%27Password%27%5D&type=

**Comment by ferventcoder** [comment]
Thanks! Github wiki is now updated. Will be a little while before it hits the website.
