### ISSUE TITLE
Document / Create PowerShell Script to Get Chocolatey.Server installed

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco-wiki#87]
It would be better to have the step by step and THEN a script that can be run to get Chocolatey.Server all set up correctly.

**Comment by pauby** [comment]
This has been documented [here](https://chocolatey.org/docs/how-to-setup-internal-package-repository#install-and-configure-chocolatey-server) - needs to updated on the [How To Setup Chocolatey.Server](https://chocolatey.org/docs/how-to-set-up-chocolatey-server). And possibly the package?
